import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ReactQueryProvider } from './react-query-provider'
import {Sidebar} from '@/components/ui/ui'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <div className="flex">
            <Sidebar />
            <div className="flex w-full h-screen p-12">{children}</div>
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
